export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const LOAD_MORE_DATA = 'LOAD_MORE_DATA';
export const LOAD_MORE_DATA_SUCCESS = 'LOAD_MORE_DATA_SUCCESS';
export const LOAD_MORE_DATA_FAILURE = 'LOAD_MORE_DATA_FAILURE';
